export * from "./about.model";
export * from "./blog.model";
export * from "./client.model";
export * from "./contact.model";
export * from "./document.model";
export * from "./founder.model";
export * from "./landing.model";
export * from "./poject.model";
export * from "./service.model";
